@baseURL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "admin2",
  "email": "admin4@email.com",
  "password": "123456"
}

###
# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "123456"
}

###
# @name create_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 3",
  "content": "Conteúdo da pergunta"
}

###
# @name fetch_recent_questions
GET {{baseURL}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta",
  "content": "Conteúdo da pergunta"
}



